trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image and run tests
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
    - script: npm install
      displayName: 'Install dependencies'
    - script: npm run cy:run
      displayName: 'Run Cypress tests'
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: your-docker-repo/your-image-name
        tags: |
          $(tag)
